import { COLORS } from "@/constants/theme"
import { StyleSheet } from "react-native"
const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#F8F9FA",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      paddingVertical: 16,
      paddingHorizontal: 16,
    },
    backButton: {
      padding: 4,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: COLORS.dark,
      marginLeft: 10
    },
    tourInfoCard: {
      flexDirection: "row",
      backgroundColor: "#fff",
      margin: 16,
      borderRadius: 16,
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    tourImage: {
      width: 150,
      height: 150,
    },
    tourInfoContent: {
      flex: 1,
      padding: 12,
      justifyContent: "center",
      marginTop: 40
    },
    tourName: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 8,
    },
    tourDetails: {
      gap: 4,
    },
    tourDetailItem: {
      flexDirection: "row",
      alignItems: "center",
    },
    tourDetailText: {
      fontSize: 14,
      color: "#666",
      marginLeft: 4,
    },
    notification: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: COLORS.blueLight,
      marginHorizontal: 16,
      marginBottom: 16,
      borderRadius: 12,
      padding: 12,
    },
    notificationContent: {
      flex: 1,
    },
    notificationMessage: {
      fontSize: 16,
      color: COLORS.primary,
      lineHeight: 20,
    },
    notificationHighlight: {
      fontWeight: "bold",
      color: COLORS.primary,
    },
    notificationImage: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginLeft: 12,
    },
    planSection: {
      backgroundColor: "#fff",
      marginHorizontal: 16,
      marginBottom: 16,
      marginTop: 30,
      borderRadius: 16,
      padding: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 5,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 16,
    },
    dateInputContainer: {
      marginBottom: 16,
    },
    dateLabel: {
      fontSize: 16,
      fontWeight: "500",
      color: "#333",
      marginBottom: 8,
    },
    dateInput: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: 1,
      borderColor: "#DDD",
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: "#F8F9FA",
    },
    dateText: {
      fontSize: 16,
      color: "#333",
    },
    datePlaceholder: {
      fontSize: 16,
      color: "#999",
    },
    confirmButton: {
      borderRadius: 12,
      paddingVertical: 14,
      alignItems: "center",
      marginTop: 8,
    },
    confirmButtonText: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#fff",
    },
    notesSection: {
      backgroundColor: "#fff",
      marginHorizontal: 16,
      marginBottom: 16,
      borderRadius: 16,
      padding: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    notesInputContainer: {
      borderWidth: 1,
      borderColor: "#DDD",
      borderRadius: 12,
      backgroundColor: "#F8F9FA",
      minHeight: 120,
      padding: 12,
      marginBottom: 16,
    },
    notesInput: {
      fontSize: 16,
      color: "#333",
      textAlignVertical: "top",
    },
    notesActions: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    attachmentButton: {
      flexDirection: "row",
      alignItems: "center",
    },
    attachmentButtonText: {
      fontSize: 14,
      color: COLORS.primary,
      marginLeft: 4,
    },
    saveNotesButton: {
      backgroundColor: COLORS.primary,
      borderRadius: 8,
      paddingVertical: 8,
      paddingHorizontal: 16,
    },
    saveNotesButtonText: {
      fontSize: 14,
      fontWeight: "bold",
      color: "#fff",
    },
    recommendationsSection: {
      marginHorizontal: 16,
      marginBottom: 16,
    },
    recommendationCard: {
      flexDirection: "row",
      backgroundColor: "#FFF8E1",
      borderRadius: 16,
      padding: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    recommendationIconContainer: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: "#FFF3E0",
      justifyContent: "center",
      alignItems: "center",
      marginRight: 16,
    },
    recommendationContent: {
      flex: 1,
    },
    recommendationTitle: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 4,
    },
    recommendationText: {
      fontSize: 14,
      color: "#666",
      lineHeight: 20,
    },
    bottomNav: {
      flexDirection: "row",
      backgroundColor: "#fff",
      paddingTop: 8,
      paddingBottom: 24,
      borderTopWidth: 1,
      borderTopColor: "#E4E6EB",
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
    },
    navItem: {
      flex: 1,
      alignItems: "center",
    },
    navText: {
      fontSize: 12,
      marginTop: 4,
      color: "#65676B",
    },
    activeNavText: {
      color: "#FF6B6B",
    },
  })
  export default styles;