import { COLORS } from "@/constants/theme";
import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#F8F9FA",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      paddingVertical: 16,
      paddingHorizontal: 16,
    },
    backButton: {
      padding: 4,
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: COLORS.dark,
    },
    coverPhotoContainer: {
      position: "relative",
      height: 200,
    },
    coverPhoto: {
      width: "100%",
      height: "100%",
    },
    profileAvatarContainer: {
      position: "absolute",
      bottom: -50,
      left: "50%",
      marginLeft: -50,
      borderRadius: 50,
      borderWidth: 4,
      borderColor: "#fff",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 5,
    },
    profileAvatar: {
      width: 100,
      height: 100,
      borderRadius: 50,
    },
    profileInfo: {
      marginTop: 60,
      alignItems: "center",
      paddingHorizontal: 16,
    },
    profileName: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#333",
    },
    profileBio: {
      fontSize: 16,
      color: "#666",
      textAlign: "center",
      marginTop: 8,
      marginBottom: 16,
      lineHeight: 22,
    },
    
    socialStats: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 16,
    },
    socialStat: {
      alignItems: "center",
      paddingHorizontal: 20,
    },
    socialStatNumber: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#333",
    },
    socialStatLabel: {
      fontSize: 14,
      color: "#666",
      marginTop: 4,
    },
    socialStatDivider: {
      width: 1,
      height: 24,
      backgroundColor: "#DDD",
    },
    profileActions: {
      flexDirection: "row",
      marginBottom: 16,
    },
    profileActionButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 8,
      paddingVertical: 8,
      paddingHorizontal: 16,
      marginHorizontal: 4,
    },
    primaryActionButton: {
      backgroundColor: COLORS.primary,
    },
    primaryActionText: {
      color: "#fff",
      fontWeight: "bold",
      marginLeft: 8,
    },
    secondaryActionButton: {
      backgroundColor: "#F0F2F5",
      borderWidth: 1,
      borderColor: COLORS.primary,
    },
    secondaryActionText: {
      color: COLORS.primary,
      fontWeight: "bold",
      marginLeft: 8,
    },
    tabsContainer: {
      flexDirection: "row",
      backgroundColor: "#fff",
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: "#DDD",
    },
    tab: {
      flex: 1,
      paddingVertical: 12,
      alignItems: "center",
    },
    activeTab: {
      borderBottomWidth: 2,
      borderBottomColor: COLORS.primary,
    },
    tabText: {
      fontSize: 14,
      color: "#666",
    },
    activeTabText: {
      color: COLORS.primary,
      fontWeight: "bold",
    },
    postsContainer: {
      padding: 16,
    },
    createPostCard: {
      backgroundColor: "#fff",
      borderRadius: 12,
      padding: 12,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    createPostHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
    },
    createPostAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginRight: 12,
    },
    createPostInput: {
      flex: 1,
      backgroundColor: "#F0F2F5",
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    createPostPlaceholder: {
      color: "#666",
    },
    createPostActions: {
      flexDirection: "row",
      borderTopWidth: 1,
      borderTopColor: "#EEE",
      paddingTop: 12,
    },
    createPostAction: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
    },
    createPostActionText: {
      marginLeft: 4,
      fontSize: 14,
      color: "#666",
    },
    postCard: {
      backgroundColor: "#fff",
      borderRadius: 12,
      marginBottom: 16,
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    postHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 12,
    },
    postUser: {
      flexDirection: "row",
      alignItems: "center",
    },
    postAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginRight: 12,
    },
    postUserName: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#333",
    },
    postTime: {
      fontSize: 12,
      color: "#666",
      marginTop: 2,
    },
    postContent: {
      fontSize: 14,
      color: "#333",
      lineHeight: 20,
      paddingHorizontal: 12,
      paddingBottom: 12,
    },
    postImage: {
      width: "100%",
      height: 300,
    },
    postStats: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: "#EEE",
    },
    postLikes: {
      flexDirection: "row",
      alignItems: "center",
    },
    likeIconContainer: {
      backgroundColor: COLORS.primary,
      width: 18,
      height: 18,
      borderRadius: 9,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 4,
    },
    statsText: {
      fontSize: 12,
      color: "#666",
    },
    postActions: {
      flexDirection: "row",
      paddingVertical: 8,
    },
    actionButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 4,
    },
    actionText: {
      fontSize: 14,
      color: "#666",
      marginLeft: 4,
    },
    aboutContainer: {
      padding: 16,
    },
    aboutCard: {
      backgroundColor: "#fff",
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    aboutTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 16,
    },
    aboutItem: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 16,
    },
    aboutIcon: {
      marginRight: 12,
    },
    aboutLabel: {
      fontSize: 12,
      color: "#666",
    },
    aboutText: {
      fontSize: 14,
      color: "#333",
      fontWeight: "500",
    },
    aboutEditButton: {
      marginLeft: "auto",
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: "#F0F2F5",
      justifyContent: "center",
      alignItems: "center",
    },
    interestsContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginBottom: 12,
    },
    interestTag: {
      backgroundColor: "#F0F2F5",
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 6,
      marginRight: 8,
      marginBottom: 8,
    },
    interestText: {
      fontSize: 14,
      color: "#333",
    },
    addInterestButton: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
    },
    addInterestText: {
      fontSize: 14,
      color: COLORS.primary,
      marginLeft: 4,
    },
    bottomNav: {
      flexDirection: "row",
      backgroundColor: "#fff",
      paddingTop: 8,
      paddingBottom: 24,
      borderTopWidth: 1,
      borderTopColor: "#E4E6EB",
    },
    navItem: {
      flex: 1,
      alignItems: "center",
    },
    navText: {
      fontSize: 12,
      marginTop: 4,
      color: "#65676B",
    },
    activeNavText: {
      color: COLORS.primary,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: '#fff',
      borderRadius: 12,
      width: '90%',
      maxWidth: 400,
      padding: 20,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    modalAvatar: {
      width: '100%',
      height: 300,
      borderRadius: 12,
      marginBottom: 20,
    },
    modalActions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 10,
    },
    modalAction: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 10,
      backgroundColor: '#f5f5f5',
      borderRadius: 8,
      minWidth: '45%',
    },
    modalActionText: {
      marginLeft: 8,
      fontSize: 14,
      color: COLORS.dark,
    },
    postOptions: {
      position: 'absolute',
      top: 40,
      right: 10,
      backgroundColor: COLORS.light,
      borderRadius: 8,
      padding: 8,
      shadowColor: COLORS.dark,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
      zIndex: 1000,
    },
    postOption: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 8,
      gap: 8,
    },
    postOptionText: {
      fontSize: 14,
      color: COLORS.dark,
    },
    postModalContent: {
      backgroundColor: COLORS.light,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 20,
      height: '85%',
      shadowColor: COLORS.dark,
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 5,
    },
    postModalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 20,
      paddingBottom: 15,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.lightGrey,
    },
    postModalTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: COLORS.dark,
    },
    postModalSave: {
      color: COLORS.primary,
      fontSize: 16,
      fontWeight: '600',
      backgroundColor: COLORS.blueLight,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
    },
    postModalBody: {
      flex: 1,
    },
    postInput: {
      borderWidth: 0,
      fontSize: 16,
      minHeight: 120,
      textAlignVertical: 'top',
      color: COLORS.dark,
      backgroundColor: COLORS.lightGrey,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
    },
    locationInput: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 12,
      backgroundColor: COLORS.lightGrey,
      borderRadius: 12,
      marginTop: 8,
      borderWidth: 1,
      borderColor: 'transparent',
    },
    locationInputFocused: {
      borderColor: COLORS.primary,
    },
    locationText: {
      marginLeft: 8,
      color: COLORS.dark,
      fontSize: 15,
    },
    postImagesPreview: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      marginTop: 20,
      paddingHorizontal: 4,
    },
    postImageContainer: {
      position: 'relative',
      width: 110,
      height: 110,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: COLORS.lightGrey,
    },
    postImagePreview: {
      width: '100%',
      height: '100%',
      borderRadius: 12,
    },
    removeImageButton: {
      position: 'absolute',
      top: 6,
      right: 6,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      borderRadius: 12,
      padding: 2,
    },
    postModalActions: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginTop: 24,
      paddingTop: 20,
      borderTopWidth: 1,
      borderTopColor: COLORS.lightGrey,
    },
    postAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: COLORS.lightGrey,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 20,
    },
    postActionText: {
      color: COLORS.primary,
      fontSize: 15,
      fontWeight: '500',
    },
    addImageButton: {
      width: 110,
      height: 110,
      borderRadius: 12,
      backgroundColor: COLORS.lightGrey,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: COLORS.primary,
      borderStyle: 'dashed',
    },
    addImageText: {
      color: COLORS.grey,
      fontWeight: "500",
    },
    editProfileButton: {
      backgroundColor: COLORS.primary,
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 8,
      marginTop: 20,
      alignSelf: 'center',
    },
    editProfileButtonText: {
      color: COLORS.light,
      fontWeight: 'bold',
      fontSize: 16,
    },
  })
  export default styles;