import { COLORS } from "@/constants/theme"
import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#fff",
    },
    mapContainer: {
      height: 200,
      position: "relative",
    },
    mapImage: {
      width: "100%",
      height: "100%",
    },
    headerOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingTop: 16,
    },
    backButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: "rgba(0, 0, 0, 0.3)",
      justifyContent: "center",
      alignItems: "center",
    },
    headerLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    favoriteButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: "rgba(0, 0, 0, 0.3)",
      justifyContent: "center",
      alignItems: "center",
    },
    tabsContainer: {
      flexDirection: "row",
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
    },
    tab: {
      flex: 1,
      paddingVertical: 12,
      alignItems: "center",
    },
    activeTab: {
      borderBottomWidth: 2,
      borderBottomColor: "#00BCD4",
    },
    tabText: {
      fontSize: 16,
      color: "#666",
    },
    activeTabText: {
      color: "#00BCD4",
      fontWeight: "600",
    },
    tourTitleContainer: {
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
    },
    tourName: {
      fontSize: 20,
      fontWeight: "bold",
      color: COLORS.primary,
      marginBottom: 8,
    },
    locationContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
    },
    locationText: {
      fontSize: 16,
      color: "#00BCD4",
      marginLeft: 4,
    },
    ratingContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
    },
    starsContainer: {
      flexDirection: "row",
      marginRight: 8,
    },
    starIcon: {
      marginRight: 2,
    },
    ratingText: {
      fontSize: 16,
      color: "#666",
    },
    priceText: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#00BCD4",
    },
    overviewContainer: {
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
    },
    sectionTitle: {
      fontSize: 22,
      fontWeight: "bold",
      color: "#000",
      marginBottom: 16,
    },
    overviewGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
    },
    overviewItem: {
      flexDirection: "row",
      alignItems: "center",
      width: "48%",
      marginBottom: 16,
    },
    overviewItemTextContainer: {
      marginLeft: 8,
    },
    overviewItemLabel: {
      fontSize: 16,
      color: "#666",
      marginBottom: 10
    },
    overviewItemValue: {
      fontSize: 18,
      fontWeight: "500",
      color: "#000",
    },
    descriptionContainer: {
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
    },
    descriptionText: {
      fontSize: 16,
      lineHeight: 22,
      color: "#333",
      marginBottom: 8,
    },
    seeMoreText: {
      fontSize: 16,
      color: "#00BCD4",
      fontWeight: "500",
    },
    destinationsContainer: {
      padding: 16,
    },
    destinationsScrollContent: {
      paddingRight: 16,
    },
    destinationItem: {
      width: 150,
      marginRight: 12,
      position: "relative",
      backgroundColor: COLORS.light,
      borderRadius: 12,
      borderWidth: 0.5,
      borderColor: COLORS.grey,
      shadowOffset: { width: 0, height: 5 },
      shadowColor: COLORS.grey,
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 4,
      paddingHorizontal: 10,
      paddingVertical: 10,
      marginBottom: 20,
    },
    destinationImage: {
      width: "100%",
      height: 120,
      borderRadius: 12,
      borderWidth: 0.5,
      borderColor: COLORS.grey,
      paddingHorizontal: 10,
      paddingVertical: 10,
    },
    destinationName: {
      fontSize: 16,
      fontWeight: "500",
      marginTop: 8,
    },
    destinationBadge: {
      position: "absolute",
      top: 8,
      right: 8,
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: "#00BCD4",
      justifyContent: "center",
      alignItems: "center",
    },
    destinationBadgeText: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#fff",
    },
    mascotContainer: {
      position: "absolute",
      bottom: 80,
      right: 16,
    },
    mascotImage: {
      width: 60,
      height: 60,
    },
    startButtonContainer: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      padding: 16,
      backgroundColor: COLORS.light,
      borderTopWidth: 1,
      borderTopColor: '#f0f0f0',
      flexDirection: 'row',
      alignItems: 'center',
      zIndex: 1000,
    },
    startButton: {
      flex: 1,
      backgroundColor: 'transparent',
      paddingVertical: 14,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: 'center',
    },
    startButtonText: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#fff",
    },
  beforeContainer: {
    padding: 16,
  },
  startLocationContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8f8f8",
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
  },
  startLocationIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  startLocationTitle: {
    fontSize: 16,
    color: "#666",
  },
  startLocationText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#000",
  },
 
  routeItem: {
    flexDirection: "row",
    marginBottom: 16,
  },
  routeNumberContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#f0f0f0",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  routeNumber: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  routeContent: {
    flex: 1,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    paddingBottom: 16,
  },
  routeName: {
    fontSize: 16,
    fontWeight: "500",
    color: "#000",
    marginBottom: 4,
  },
  routeDescription: {
    fontSize: 16,
    color: "#666",
  },
  viewMapButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
  },
  viewMapText: {
    fontSize: 16,
    fontWeight: "500",
    color: COLORS.primary,
    marginLeft: 8,
  },

  reviewsContainer: {
    padding: 16,
  },
  ratingOverview: {
    alignItems: "center",
    marginBottom: 16,
  },
  ratingBig: {
    fontSize: 36,
    fontWeight: "bold",
    color: "#000",
  },
  ratingStarsContainer: {
    flexDirection: "row",
    marginVertical: 8,
  },
  ratingCount: {
    fontSize: 16,
    color: "#666",
  },
  ratingBars: {
    marginBottom: 24,
  },
  ratingBarContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  ratingBarLabel: {
    width: 20,
    fontSize: 16,
    fontWeight: "500",
    color: "#666",
    marginRight: 8,
  },
  ratingBarBackground: {
    flex: 1,
    height: 8,
    backgroundColor: "#f0f0f0",
    borderRadius: 4,
    overflow: "hidden",
  },
  ratingBarFill: {
    height: "100%",
    backgroundColor: "#FFD700",
    borderRadius: 4,
  },
  reviewsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  filterButton: {
    padding: 4,
  },
  reviewItem: {
    marginBottom: 16,
    padding: 16,
    backgroundColor: "#f8f8f8",
    borderRadius: 8,
  },
  reviewHeader: {
    flexDirection: "row",
    marginBottom: 12,
  },
  reviewerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  reviewerInfo: {
    flex: 1,
  },
  reviewerName: {
    fontSize: 16,
    fontWeight: "500",
    color: "#000",
    marginBottom: 4,
  },
  reviewRating: {
    flexDirection: "row",
  },
  reviewStarIcon: {
    marginRight: 2,
  },
  reviewTime: {
    fontSize: 16,
    color: "#999",
  },
  reviewComment: {
    fontSize: 16,
    lineHeight: 20,
    color: "#333",
    marginBottom: 12,
  },
  reviewActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.lightGrey,
    paddingTop: 10,
  },
  actionButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: COLORS.lightGrey,
    marginLeft: 10,
  },
  deleteButton: {
    backgroundColor: '#FFEBEE',
  },
  actionText: {
    fontSize: 14,
    color: COLORS.darkGrey,
    fontWeight: '500',
  },
  deleteText: {
    color: COLORS.red,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: COLORS.light,
    borderRadius: 12,
    padding: 20,
    width: '90%',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    marginBottom: 20,
    color: COLORS.dark,
  },
  tourInfoContainer: {
    width: '100%',
    marginBottom: 20,
  },

  tourPrice: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'black',
    marginBottom: 4,
  },
  tourDuration: {
    fontSize: 16,
    color: COLORS.grey,
  },
  paymentMethodContainer: {
    width: '100%',
    marginBottom: 20,
  },
  paymentMethodTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.dark,
    marginBottom: 12,
  },
  walletInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.light,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.grey,
  },
  walletLeft: {
    flex: 1,
  },
  walletName: {
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.dark,
    marginBottom: 4,
  },
  walletBalance: {
    fontSize: 16,
    color: COLORS.grey,
  },
  changeText: {
    fontSize: 16,
    color: COLORS.primary,
    fontWeight: '500',
  },
  totalContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.grey,
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.dark,
  },
  totalAmount: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  purchaseButton: {
    width: '100%',
    padding: 16,
    borderRadius: 8,
    marginBottom: 12,
  },
  purchaseButtonText: {
    color: COLORS.light,
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
  },
  secureText: {
    fontSize: 12,
    color: COLORS.grey,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 16,
  },
  closeText: {
    fontSize: 22,
    color: COLORS.dark,
    fontWeight: 'bold',
    paddingHorizontal: 4,
  },
  tourInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 8,
    backgroundColor: '#f5f6fa',
    padding: 10,
    borderRadius: 10,
  },
  tourDesc: {
    color: COLORS.grey,
    fontSize: 16,
  },
  paymentMethodHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginTop: 16,
    marginBottom: 8,
  },
  walletBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f6fa',
    borderRadius: 10,
    padding: 10,
    marginBottom: 16,
    width: '100%',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 16,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 12,
  },
  secureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  // New styles for tour detail screen UI
  tabContentWrapper: {
    flex: 1,
    backgroundColor: COLORS.light,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: 'hidden',
    marginTop: -30,
  },
  startButtonWrapper: {
    flex: 1,
    marginLeft: 10,
  },
  priceDisplayContainer: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.transparent,
    marginRight: 10,
    marginLeft: 10,
  },
  priceDisplayText: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  startButtonGradient: {
    flex: 1,
    borderRadius: 8,
  },
  modalTextInput: {
    borderWidth: 1,
    borderColor: COLORS.grey,
    borderRadius: 8,
    padding: 10,
    width: '100%',
    minHeight: 100,
    textAlignVertical: 'top',
    marginBottom: 20,
    fontSize: 16,
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  modalButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: COLORS.lightGrey,
    marginRight: 10,
  },
  saveButton: {
    backgroundColor: COLORS.primary,
    marginLeft: 10,
  },
  cancelButtonText: {
    color: COLORS.dark,
    fontWeight: 'bold',
  },
  saveButtonText: {
    color: COLORS.white,
    fontWeight: 'bold',
  },
  })
  