name: Web Mobile Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /root/services/Audivia-Frontend-Side-web/Audivia
          git fetch origin
          git checkout main
          git pull
          docker build -t audivia-web .
          docker stop audivia-web-container || true
          docker rm audivia-web-container || true
          docker run -d --name audivia-web-container -p 3001:80 audivia-web
            
          
